version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=mysql://root:mysql123@172.20.1.60:3306/nextjs-prisma
    ports:
      - 3000:3000
    depends_on:
      - mysql-service

  mysql-service:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: mysql123
      MYSQL_DATABASE: nextjs-prisma
    ports:
      - 3306:3306
    # volumes:
    #   - dados:/usr/dados

  front:
      build:
        context: C:\Users\leone\OneDrive\Área de Trabalho\Projetos\React\Nova pasta\aula-03\.
        dockerfile: Dockerfile
      environment:
        - DATABASE_URL=http://172.20.1.60:3000
      ports:
        - 5173:80
      depends_on:
        - app